version: "3.9"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - database
    restart: on-failure
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go-jwt-auth
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  db: